name: Qlottery
version: 1.0.0-RC.3
main: com.quietwind01.QLottery
api-version: 1.20

depend: [Vault]

commands:
  ql:
    description: The base command for QLottery.
    usage: /ql <subcommand>
    permission: qlottery.*
    children:
      ticket:
        description: Buy or sell tickets.
        usage: /ql ticket <buy|sell> <amount>
        permission: qlottery.ticket
      tickets:
        description: Standalone command that tells the player how many tickets they own.
        usage: /ql tickets
        permission: qlottery.ticket.count
      pool:
        description: View the amount of money in the pool.
        usage: /ql pool amount
        permission: qlottery.pool
      stats:
        description: View the QLottery stats for yourself and the server.
        usage: /ql stats
        permission: qlottery.stats